### ISSUE TITLE
Xác định yêu cầu phi chức năng

### ISSUE THREAD

**Issue by NapsterDinh** [vithuydiep/FastDeliveryApplication#10]

**Comment by Khang11102000** [comment]
- Thời gian cho những thao tác không quá 2 giây (Nếu quá thì cần bảo trì để khắc phục).
- Hoạt động hiệu quả ngay khi có 10000 tài khoản cùng sử dụng dịch vụ.
- Tiêu tốn ít tài nguyên phần cứng như bộ nhớ (100 - 150 mb).
- Giao diện bắt mắt, phù hợp với điều kiện sáng lẫn tối (Sử dụng tone màu tối tránh bị chóa mắt).
- Thường xuyên bảo trì để đảm bảo các tính năng vẫn hoạt động hiệu quả hiệu quả. 
- Chịu trách nhiệm về bảo mật và sửa chữa sai sót một cách nhanh chóng.
- Tương thích với nhiều hệ điều hành (Đặc biệt là Android và iOS).
- Phù hợp với pháp luật, quy chuẩn xã hội (Tránh sử dụng các hình ảnh tuyên truyền trái đạo đức, pháp luật).
