### ISSUE TITLE
Đặc tả yêu cầu phần mềm sử dụng bảng (Mô tả action trong ngôn ngữ có cấu trúc )

### ISSUE THREAD

**Issue by vithuydiep** [vithuydiep/FastDeliveryApplication#12]
Viết đặc tả yêu cầu phần mềm sử dụng bảng

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/TableStructure.pdf
Mô tả cấu trúc dạng bảng

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_TableStructure.pdf

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_TableStructure.pdf
cập nhật lại link sau khi thêm thư mục Document
