### ISSUE TITLE
Đặc tả yêu cầu phần mềm sử dụng usecase

### ISSUE THREAD

**Issue by vithuydiep** [vithuydiep/FastDeliveryApplication#13]
Vẽ yêu cầu phần mềm bằng cách vẽ usercase

**Comment by Khang11102000** [comment]
[UsecaseUser.pdf](https://github.com/vithuydiep/FastDeliveryApplication/files/6216760/UsecaseUser.pdf)

**Comment by Khang11102000** [comment]
[Usecase.pdf](https://github.com/vithuydiep/FastDeliveryApplication/files/6216775/Usecase.pdf)

**Comment by Khang11102000** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/Usecase.pdf

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_Usecase.pdf
