### ISSUE TITLE
Thiết kế lược đồ Class Diagram

### ISSUE THREAD

**Issue by vithuydiep** [vithuydiep/FastDeliveryApplication#16]

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/ClassDiagram.pdf

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_ClassDiagram.pdf

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_ClassDiagram.pdf
cập nhật lại link sau khi thêm thư mục document
