### ISSUE TITLE
Requirement Document

### ISSUE THREAD

**Issue by vithuydiep** [vithuydiep/FastDeliveryApplication#20]

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/RequirementDocument.pdf

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_RequirementDocument.pdf

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_RequirementDocument.pdf
cập nhật lại link sau khi thêm thư mục Document
