### ISSUE TITLE
Chức năng Đăng ký

### ISSUE THREAD

**Issue by quockhanhtn** [vithuydiep/FastDeliveryApplication#29]
### Issue cần thực hiện trước (1)

- [Xử lý Đăng nhập](https://github.com/vithuydiep/FastDeliveryApplication/issues/28)

### Công việc

- Validate thông tin người dùng nhập vào
- Tạo tài khoàn và xác thực trước khi đăng nhập

**Comment by NapsterDinh** [comment]
Hoàn thành chức năng đăng ký với vai trò là người dùng
Xác thực số điện thoại bằng OTP trước khi đăng ký
