### ISSUE TITLE
Chức năng Quên mật khẩu

### ISSUE THREAD

**Issue by quockhanhtn** [vithuydiep/FastDeliveryApplication#30]
### Issue cần thực hiện trước (2)

- [Chức năng Đăng nhập](https://github.com/vithuydiep/FastDeliveryApplication/issues/28)
- [Chức năng Đăng ký](https://github.com/vithuydiep/FastDeliveryApplication/issues/28)

### Công việc

- Validate tài khoản có tồn tại trong hệ thống không
- Xác minh qua email hoặc otp trên điện thoại
- Cho người dùng đổi mật khẩu mới

**Comment by NapsterDinh** [comment]
Kiểm tra tính tồn tại của số điện thoại
Xác minh số điện thoại đó bằng OTP
Cho phép thay đổi mật khẩu
