### ISSUE TITLE
Phân tích yêu cầu người sử dụng và yêu cầu hệ thống

### ISSUE THREAD

**Issue by NapsterDinh** [vithuydiep/FastDeliveryApplication#8]

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/RequirementFunction.pdf
Chưa hoàn thiện

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/RequirementFunction.pdf 
Cập nhật thêm chức năng

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/RequirementFunction.pdf
Đã cập nhật chức năng

**Comment by vithuydiep** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_RequirementFunction.pdf

**Comment by NapsterDinh** [comment]
https://github.com/vithuydiep/FastDeliveryApplication/blob/main/document/Group04_RequirementFunction.pdf
cập nhật lại link sau khi thêm thư mục Document
